<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;


class ArtikelTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('articles')->insert([
            [
                'judul' => 'DIGITALIZATION OF MENGKARANG GEOPARK MINIATURE UNIVERSITAS JAMBI AS AN EFFORT TO SUPPORT THE SUMMER COURSE PROGRAM',
                'penulis' => 'Hari Wiki Utama, Rakhmatul Arafat, Bagus Adhitya, Yulia Morsa Said, Jarot Wiratama, Mega Aulia, Dhinda Ayu',
                'foto_artikel' => '',
                'abstract' => 'Perkembangan ilmu pengetahuan di era Revolusi Industri 4.0 dan Society 5.0 merupakan fenomena yang serba digital, termasuk ilmu kebumian. Konsep ini menggunakan ilmu pengetahuan berbasis kecerdasan buatan untuk kebutuhan pendidikan yang serba cepat dan nyaman. Kaitannya dengan bidang pendidikan ilmu kebumian adalah studi tentang fenomena bentang alam dan singkapan batuan sebagai hasil dari proses alamiah. Situasi Universitas Jambi yang jauh dari keberadaan singkapan batuan sebagai objek pembelajaran memberikan tantangan besar untuk dapat mengidentifikasi batuan yang ada dengan cepat. Keberadaan miniatur Geopark Mengkarang di Universitas Jambi dapat menjadi solusi yang efektif dalam pembelajaran di bidang kebumian. Sehingga, melalui digitalisasi dapat menjadi alternatif yang diminati dalam media pembelajaran, khususnya untuk kegiatan short summer course yang berkaitan dengan geopark. Upaya digitalisasi ini merupakan bagian dari kegiatan pengabdian dan peran serta civitas akademika Universitas Jambi dalam melakukan inovasi pembelajaran. Dalam pelaksanaan kegiatan pengabdian ini pengumpulan data dilakukan dengan mendeskripsikan 28 sampel batuan dari Kawasan UNESCO Global Geopark Merangin Jambi. Digitalisasi meliputi pembuatan label informasi untuk setiap tampilan batuan yang dilengkapi dengan barcode untuk memudahkan akses. Akses ini bertujuan untuk memberikan informasi yang lebih detail mengenai proses pembentukan setiap batuan. Kegiatan pengabdian ini secara signifikan berkontribusi dalam mendukung kegiatan summer course di Fakultas Sains dan Teknologi, Universitas Jambi. Selain membantu kegiatan summer course, diharapkan melalui digitalisasi ini, Universitas Jambi dapat memainkan peran penting dalam mendukung situs yang telah diakui sebagai situs warisan dunia oleh UNESCO ini.',
                'file_path' => 'https://journal.uinmataram.ac.id/index.php/transformasi/article/view/8590/3002',
            ],
            [
                'judul' => 'PALEOVOLCANIC KARING RECONSTRUCTION IN THE MERANGIN JAMBI UNESCO GLOBAL GEOPARK TERRITORY BASED ON PETROLOGICAL AND GEOCHEMICAL APPROACH',
                'penulis' => 'Hari Wiki Utama, Sutarto, Asmoro Widagdo, Eko Wahyudi',
                'foto_artikel' => '',
                'abstract' => 'The presence of lava and pyroclastic sequences in the Karing River on the Merangin Jambi UNESCO Global Geopark territory provides information about the existence of ancient volcanoes. The absence of confirmed rock formations from the distribution of volcanic rock products that have been mapped nationally and also the shape of this ancient volcanic body, is an important reason for this research to be carried out using a petrological approach using petrography and XRF gochemical methods. Petrographic analysis is an appropriate method to determine the mineralogy consist, textures and particular textures, rock structures that are confirmed from field data. Meanwhile, a geochemical approach is used to determine rock oxide compounds. This method aims to reconstruct the shape and type of volcanoes. Research data shows that there are four lava sequences, with Sequence 1 having an entablature structure, Sequence 2 and Sequence 3 having a flow structure, and Sequence 4 having a vesicular-flow structure. The petrography results show that Sequence 1 and Sequence 2 are composed of phenocrysts and microliths of plagioclase, olivine, clinopyroxene, orthopyroxene. Meanwhile, in Sequence 3, hornblende is present, and in Sequence 4, the mineral olivine is absent. The results of geochemical analysis from the four lava sequences are in basalt rocks with 40%-50% Silica content, Calk-alkali basalt magma series, petrogenesis interpreted from the convergence of oceanic subduction beneath continent. The pyroclastic rocks found at the bottom of the lava sequence are evidence of the stratigraphic structure that makes up a volcano originating from the Karing Paleovolcanic, while the pyroclastic rocks found at the top of the lava sequence are believed to originate from other ancient volcanic eruptions. With the stratigraphy composed of lava and pyroclastic sequences, it can be concluded that this ancient volcano is a strato volcano type which is relatively sloping and almost resembles a shield volcano.',
                'file_path' => 'https://mail.online-journal.unja.ac.id/jop/article/view/28588/16633',
            ],
            [
                'judul' => 'PERAN PERGURUAN TINGGI DALAM PEMBANGUNAN KEBERLANJUTAN GEOPARK DI UGGp MERANGIN JAMBI',
                'penulis' => 'Hari Wiki Utama, Misnawati, Anggi Deliana Siregar, Feby Febiyora Chandra Kirana, Eko Wahyudi, D.M. Magdalena Ritonga, Leni Marlina',
                'foto_artikel' => '',
                'abstract' => 'Perguruan tinggi merupakan satu aktor penting dalam pembangunan Geopark Merangin Jambi menjadi UNESCO Global Geopark Merangin Jambi. Pembangunan berkelanjutan di kawasan geopark melibatkan masyarakat lokal sebagai hal yang terpenting di dalam geopark. Perguruan tinggi dalam kegiatan tri dharma dapat diaplikasi dalam kegiatan pengabdian kepada masyrakat yang terkait dengan geopark, dalam hal ini sebagai upaya edukasi dan konservasi warisan geologi yang ada di kawasan geopark. Pelaksanaan pengabdian melibatkan sivitas akademika Universitas Jambi, Badan Pengelola Geopark Merangin Jambi, Universitas Merangin, dan Pemerintah Kabupaten Merangin serta Pemerintah Provinsi Jambi. kegiatan pengabdian yang dilakukan seperti Geopark Goes to School, Campus Goes to Geopark, Keterampilan Masyrakat, dan Konferensi Internasional. Berdasarkan kegiatan yang telah dilakukan, bahwa kegiatan pengabdian ini dapat terlaksana dengan baik dalam bentuk konsep edukasi dan konservasi pada warisan geologi dalam tiga pilar penting dari geopark, yaitu kenaekaragaman geologi, kenaekaragaman hayati, dan keanekaragaman budaya. Dalam pelaksanaan kegiatan pengabdian ini dapat disimpulkan bahwa pentingnya peran perguruan tinggi terhadap pembangunan yang berkelanjutan di Kawasan UNESCO Global Geopark Merangin Jambi.',
                'file_path' => '',
            ],
            [
                'judul' => 'Geologi dan Lingkungan Pengendapan Batupasir Formasi Talang Akar Daerah Lubuk Mandarsah Kecamatan Tengah Ilir Kabupaten Tebo, Provinsi Jambi',
                'penulis' => 'Anggi Deliana Siregar, Fenny Dwi Utari Sy, Aisyah Indah Irmaya',
                'foto_artikel' => '',
                'abstract' => 'Daerah Lubuk Mandarsah termasuk ke dalam Cekungan Sumatera Selatan Sub cekungan Jambi. Stratigrafi di daerah penyelidikan terdiri dari Formasi Lahat, Formasi Talangakar, Formasi Gumai, Formasi Airbenakat. Metodologi penelitian yang dilakukan adalah melakukan metoda pemetaan langsung dengan cara melakukan observasi lapangan untuk memetakan persebaran litologi pada daerah penelitian. Sebelum dilakukan observasi lapangan terlebih dahulu dilakukan analisis data sekunder yang didapatkan dari pustaka dan sumber-sumber lain yang dapat digunakan sebagai bahan pertimbangan sebelum melakukan observasi lapangan secara detail, yang kemudian akan dibantu dengan pekerjaan laboratorium. Berdasarkan hasil pengamatan lapangan, pada formasi talangakar ini terdapat batupasir yang membentang dari Tenggara sampai ke Barat laut daerah penelitian dan tersebar sebesar 50% dari daerah penelitian. Formasi Talangakar ini memiliki litologi batupasir berwarna abu-abu terang dengan struktur laminasi, massif, dan wavy laminasi. Memiliki ukuran butir sedang sampai sangat halus, dengan derajat kebundaran agak membundar sampai membundar terpilah baik, kemas tertutup, dengan fragmen kuarsa, matrik lempung semen silika. Hasil dari analisis lapangan dan analisis profil akan dikaitkan dengan klasifikasi lingkungan pengendapan yang mengacu kepada klasifikasi Allen dan Chambers (1998). Berdasarkanmetode yang digunakan, daerahpenelitianterdapat di lingkungan pengendapan delta front dan delta plain.',
                'file_path' => 'https://mail.online-journal.unja.ac.id/jtk/article/view/30898',
            ],
            [
                'judul' => 'IMPLEMENTATION OF INTERNET OF THINGS (IoT) BASED ON GOOGLE SHEETS FOR WATER QUALITY MONITORING SYSTEM',
                'penulis' => 'Jesi Pebralia, Linda Handayani, Dawam Suprayogi, Iful Amri',
                'foto_artikel' => '',
                'abstract' => 'Temperature, pH, and total dissolved solid (TDS) are important indicators of water quality that affect various aspects. This research aims to develop a water quality monitoring system by implementing Internet of Things (IoT) technology based on Google Sheets. Based on the tests for each sensor - temperature, pH, and TDS - the results show that the system has an excellent level of measurement precision, with an average precision value of above 95%. The findings also indicate that Google Sheets can be utilized in IoT technology and can operate on more than one distinct computer device at the same time. The use of Google Sheets in IoT technology is highly effective, flexible, and user-friendly. The measured data can be automatically stored and can be visualized effectively.".',
                'file_path' => 'https://online-journal.unja.ac.id/jop/article/view/28689/16636',
            ],
            [
                'judul' => 'Geochemical Data for Geothermal Exploration on Grao Sakti, Jambi, Indonesia',
                'penulis' => 'Hari Wiki Utama, Yulia Morsa Said, Anggi Deliana Siregar, Bagus Adhitya dan Agus Kurniawan Mastur',
                'foto_artikel' => '',
                'abstract' => 'Sumatra has more than 20 geothermal areas the associated with Sumatra Fault System and volcanic system along Barisan Range. Grao Sakti is a geothermal area in Renah Kemumu, Jangkat District, Merangin Regency, Jambi, such a characteristic. Geochemical data is a part of early geothermal exploration for identification fluid type, estimating temperature geothermal reservoir, and assessment geothermal system. We used two geothermal fluids manifestation sample for geochemical analyzed. These three methods for determining fluids geothermal characteristic, including of geothermal fluids type, geothermal of partial chemical equilibrium, and solute geotermometers. Geothermal manifestation is consist of geyser and hot spring with temperature about 66.8°C - 91.5°C. The result analysis Cl-SO4-HCO3 to show chloride fluid type, as indicated of fluid geothermal reservoir. Geothermal fluid of Na-K-Mg on partial chemical equilibrium as clue geothermal fluids of boiling condition. Solute geotermometers used to approach silica geotermometer about 146.50°C - 72.24°C, while solute sodium-potassium geothermometer about 203.19°C - 206.18°C. Geothermal fluids of geochemical analysis as hint geothermal reservoir temperature and the geothermal reservoir was classified medium temperature, which is potential for geothermal energy resource and electricity with binary system. The review of geological setting, this area is classified as a volcano-tectonic geothermal system with liquid dominated reservoir.',
                'file_path' => 'https://pubs.aip.org/aip/acp/article-abstract/2482/1/010001/2867256/Preface-The-3rd-International-Conference-on?redirectedFrom=fulltext',
            ],
            [
                'judul' => 'MODIFICATION OF NATURAL ZEOLITE FROM BOGOR FOR HYDROGEN STORAGE',
                'penulis' => 'Silvester Tursiloadi, Aan Wahyuni, Lenny Marlinda, Muhammad Safaat, Latifa Hauli, Wiyanti Fransisca Manulang, Amalia Kurnia Amin, Deni Shidqi Khaerudini and Muhammad Al Muttaqii',
                'foto_artikel' => '',
                'abstract' => 'Using hydrogen as an energy source still needs improvement, especially in storing hydrogen. Zeolite is a material with a large surface area and high porosity. When NaOH is added to natural zeolite Bogor, it breaks down into microporous (2 nm) and mesoporous (2–50 nm) zeolite. This zeolite with two different sizes of pores is called hierarchical zeolite. The wet impregnation method mixed Ni with zeolite using Ni(NO3).6H2O, which lets H2 adsorb through a spillover mechanism. The characterization of the materials was analyzed using a Particle Size Analyzer (PSA), X-ray diffraction (XRD), and a Surface Area Analyzer (SAA). Temperature-programmed desorption-H2 (TPD-H2) determined the adsorption capacity for H2 gas. The adsorption capacity of H2 for different adsorption times (30, 45, 60, 75, and 90 min) was 0.1745, 0.3620, 0.7624, 0.2333, and 0.1802wt%, respectively. The highest adsorption capacity is 0.7624 wt.% with 60 min of adsorption time. When Ni metal was added to zeolite, it blocked or clogged the pores, lowering the adsorption capacity to 0.1405 wt.% and making H2 adsorption less efficient.',
                'file_path' => 'https://www.researchgate.net/profile/Muhammad-Al-Muttaqii/publication/377236511_MODIFICATION_OF_NATURAL_ZEOLITE_FROM_BOGOR_FOR_HYDROGEN_STORAGE/links/659c9c732468df72d3043424/MODIFICATION-OF-NATURAL-ZEOLITE-FROM-BOGOR-FOR-HYDROGEN-STORAGE.pdf',
            ],
            [
                'judul' => 'Releasing bend structures of Dikit fault segment on Grao Sakti, Jambi: Its related STRIKE-slip fault zone',
                'penulis' => 'Hari Wiki Utama, Yulia Morsa Said and Anggi Deliana Siregar',
                'foto_artikel' => '',
                'abstract' => 'The Dikit fault segment is part of Sumatran Fault Zone on Grao Sakti, Merangin Regency, Jambi, Indonesia. It has been subjected of scientific research interest for decaded. The geothermal manifestations appears along fault segmented and structural features are the principal displacement zone and related to strike slip fault zone. This fault segmented is related strike slip fault zone, where flowing Grao stream. This paper aim to understanding releasing bend structure process the related strike slip fault zone of Dikit fault segmented. Structural element measurement was employed to determine the orientation of structural and the dynamics of the structures. Each structural element measured attempt to analyzed for understanding the structural evolustion of Dikit fault segment. The integration to structural element measured and structural analysis to generate of structural model the releasing bend structure of Dikit fault segment. The stratigraphy is composed of Oligo-Miocene Andesitic Lava-Volcanic Breccia, Pleistocene Granitic Intrusion, and Old Masurai Volcanic Dacitic Lava. The results of research area show that fault orientation of approximately in NW - SE direction, which is right slip fault and normal right slip fault. Dikit fault segment is generate tectonics setting in Sumatra and global estuation. The followed opening Andaman Sea and eventually structural path formation on Barisan Range since Middle Miocene. It is believed, that the Dikit Fault of strike slip fault. Several locations along the fault segmented were appear geothermal features and Pleistocene granitic intrusion on Grao Sakti. This is a trigerring of deformation mechanism of strike slip-fault toward releasing bend structures.',
                'file_path' => 'https://pubs.aip.org/aip/acp/article-abstract/2482/1/010001/2867256/Preface-The-3rd-International-Conference-on?redirectedFrom=fulltext',
            ],
            [
                'judul' => 'Kelimpahan Perifiton pada Substrat Alami di Air Terjun Muara Karing Kawasan Geopark Merangin Jambi',
                'penulis' => 'Dhiny Amatullah, Tedjo Sukmono, Mahya Ihsan, Tia Wulandari, Dawam Suprayogi',
                'foto_artikel' => '',
                'abstract' => 'Air terjun Muara Karing termasuk ke dalam kawasan Geopark Merangin yang menjadi tujuan wisata alam. Di Kawasan Air Terjun Muara Karing, perifiton yang menempel pada substrat batuan menjadi produsen dalam ekosistem lotik. Beradaptasi dengan lingkungan air yang deras, perifiton mampu bertahan di dasar berbatu yang melimpah di Kawasan Air Terjun Muara Karing Geopark Merangin. Penelitian ini akan mengeksplorasi kelimpahan perifiton pada substrat batu di Air Terjun Muara Karing untuk memberikan informasi tentang keanekaragaman biologi di kawasan tersebut. Penelitian ini dilaksanakan pada Oktober 2022-Juni 2023 dengan metode purposive sampling. Data mengenai kelimpahan perifiton dan faktor-faktor abiotik perairan telah dirangkum dalam tabel untuk menunjukkan nilai-nilai di tiap stasiun. Kemudian, data ini dianalisis secara deskriptif. Secara keseluruhan kelimpahan perifiton yang didapatkan yaitu sebanyak 2.505 individu /125cm2 dari ketiga stasiun dengan uraian secara berurutan yaitu 1.554; 461; dan 490 individu /125cm2. Diperoleh 17 jenis perifiton yang termasuk ke dalam dua kelas, yaitu Bacillariophyceae (99,72%) dan Zygnematophyceae (0,28%).',
                'file_path' => 'https://ojs.unsulbar.ac.id/index.php/bioma/article/view/3637',
            ],
        ]);
    }
}
